<!DOCTYPE html>
<html>
<head>
	<title>JavaScript</title>
<body>
	<h2>JavaScript Async and wait</h2>
	<label for="balance">Account Balance:</label><br>
	<input type="number" id="balance" placeholder="Enter Your Balance"><br><br>
	<label for="amount">Withdraw Amount</label><br>
	<input type="number" id="amount" placeholder="Enter amount to withdraw"></br><br>
	<button onclick="handleATMWithdrawal()">WithDraw</button>
	<div id="result"></div>
	<script>
		function withdrawFromATM(accountBalance,amountToWithdraw)
		{
			return new Promise((resolve,reject)=>
			{
			document.getElementById("result").innerText="Processing Your Transactions"
			setTimeout(()=>
			{
			if (amountToWithdraw<=accountBalance)
			{
				resolve(`Withdrawal successful!${amountToWithdraw} display`)
			}
			else
			{
				reject(`Insuficcient funds. Your balance is ${accountBalance}`)
			}
			},2000);
			});
		}
		async function handleATMWithdrawal()
		{
			const balance=parseFloat(document.getElementById("balance").value)
			const amount=parseFloat(document.getElementById("amount").value)
			if (isNaN(balance)|| isNaN(amount))
			{
				document.getElementById("result").innerText="Please Enter value"
				return;
			}
			try
			{
				const message=await withdrawFromATM(balance,amount);
				document.getElementById("result").innerText=message;
			}
			catch(error)
			{
				document.getElementById("result").innerText=error;
			}
		}
	</script>
	<p id="p1">
	<h2>Exception handling</h2>
	<script>
		try
		{
			let numbers=[1,2,3,null,5];
			let result=numbers.map(num=>{if (num===null ) throw new Error("Null Cannot be empty****")
			return (num*2)});
			console.log(result)
		}
		catch (error)
		{
			console.error("Exception",error.message);
		};
	</script>
	
</body>
</html>